import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
const font = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cointab - Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={`${font.className} bg-gray-50`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
